# TO RUN DOCKER IMAGE LOCALLY
# docker pull raghavendiran2002/cicd:main
# docker run -p 127.0.0.1:3000:3000 docker.io/raghavendiran2002/cicd:main
name: Dockerize Node.js Application
on: push
jobs:
  build-container:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: raghavendiran2002/cicd

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            #Now we have got the access of EC2 and we will start the deploy .
            sudo su &&
            git clone git@github.com:Raghavendiran-2002/cicd-aws-docker
            cd /home/ubuntu/cicd-aws-docker/ &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            sudo npm i &&
            sudo docker-compose up &&
            sudo docker-compose up 
          '

    # name: Build Docker container image
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Publish to Docker Hub
    #     uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #     with:
    #       username: ${{secrets.DOCKER_USERNAME}}
    #       password: ${{secrets.DOCKER_PASSWORD}}
    #       repository: raghavendiran2002/cicd
    #       tag: latest, ${{github.run_number}}
