# TO RUN DOCKER IMAGE LOCALLY
        # docker pull raghavendiran2002/cicd:main
        # docker run -p 127.0.0.1:3000:3000 docker.io/raghavendiran2002/cicd:main
name: Dockerize Node.js Application
on: push
jobs:
  build-container:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: raghavendiran2002/cicd
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



    # name: Build Docker container image
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Publish to Docker Hub
    #     uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #     with:
    #       username: ${{secrets.DOCKER_USERNAME}}
    #       password: ${{secrets.DOCKER_PASSWORD}}
    #       repository: raghavendiran2002/cicd
    #       tag: latest, ${{github.run_number}}
